data_dir: "./data/arxiv_papers"
model_dir: "./models"
vector_db_path: "./vector_store/cvpr_db"
arxiv_query: "cat:cs.CV AND submittedDate:[2023 TO 2024]"
chunk_size: 512
chunk_overlap: 100
embedding_model: "all-MiniLM-L6-v2"
